### ISSUE TITLE
String manipulation awesome config

### ISSUE THREAD

**Issue by elythh** [osmarmora05/dotfiles#1]
Hey, I love your dotfile. I tried using it on my personal laptop and it looks awesome.
However, I found a little bug that was causing a lot of notifications.
In the two file `signals/system/volume.lua` and `signals/system/microphone.lua` you attempt to multiply a string by 100 before converting it to an int.

```lua
            local volume     = string.match(stdout:match('(%d%.%d+)') * 100, '(%d+)')
            local muted      = stdout:match('MUTED')
            local muted_int  = muted and 1 or 0
            local volume_int = tonumber(volume) -- integer 
```

I think you should rather first extract the string then convert it to an int and multiply it

```lua
            local volume     = string.match(stdout:match('(%d%.%d+)'), '(%d+)')
            local muted      = stdout:match('MUTED')
            local muted_int  = muted and 1 or 0
            local volume_int = tonumber(volume) * 100 -- integer 
```

It's really a small detail however. Keep up the great work !

**Comment by osmarmora05** [comment]
Hi. Sorry for the delay; I have had some problems with the wifi xd. I've tried your suggestion and recorded a video to show you my attempts and the code I used:

https://github.com/osmarmora05/dotfiles/assets/101274294/e7f23de4-49ec-4737-81f1-cdb461137363

I'd love for you to check it out and give me your feedback on how it worked. This is the code I used in `signals/system/volume.lua`:

```lua
local function volume_emit()
    awful.spawn.easy_async_with_shell(
        "bash -c 'wpctl get-volume @DEFAULT_AUDIO_SINK@'", function(stdout)
            local volume     = string.match(tonumber(stdout:match('(%d%.%d+)')) * 100, '(%d+)')
            local muted      = stdout:match('MUTED')
            local muted_int  = muted and 1 or 0
            local volume_int = tonumber(volume)  -- integer 
            if volume_int ~= volume_old or muted_int ~= muted_old then
                awesome.emit_signal('signal::volume', volume_int, muted) -- integer
                volume_old  = volume_int
                muted_old   = muted_int
            end
        end)
end
```
If you have any advice or any workarounds, it will be greatly appreciated!

**Comment by elythh** [comment]
That's really odd because whenever I try to manipulate `volume` I get spammed with this lua error
![image](https://github.com/osmarmora05/dotfiles/assets/50964650/7f53c2e8-b652-43ec-b64e-4a36f4646f5f)
Could it be because of my lua/awesome version ?

Here's what I'm using 
```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 ```

**Comment by osmarmora05** [comment]
When you run this command `bash -c 'wpctl get-volume @DEFAULT_AUDIO_SINK@'` in your `shell,` what does it return?

**Comment by elythh** [comment]
![image](https://github.com/osmarmora05/dotfiles/assets/50964650/16009b75-96ba-49c3-89cd-a2fc91d80c5a)
Looks fine to me

**Comment by elythh** [comment]
So you're right something is wrong with the result I get from `wpctl get-volume @DEFAULT_AUDIO_SINK@`

**Comment by osmarmora05** [comment]
try this


```lua
local function volume_emit()
    awful.spawn.easy_async_with_shell(
        "bash -c 'wpctl get-volume @DEFAULT_AUDIO_SINK@'", function(stdout)
            local volume_match = string.match(stdout:match('(%d%.%d+)'), '(%d+)')
            local volume     = tonumber(volume_match) * 100
            local muted      = stdout:match('MUTED')
            local muted_int  = muted and 1 or 0
            local volume_int = tonumber(volume) -- integer 
            if volume_int ~= volume_old or muted_int ~= muted_old then
                awesome.emit_signal('signal::volume', volume_int, muted) -- integer
                volume_old  = volume_int
                muted_old   = muted_int
            end
        end)
end
```

**Comment by elythh** [comment]
Nop, I'm unable to get the current volume

Thanks a lot for your help tho, in the end it was something on my side and not with your config 😅 

I think I'll stick with pulseaudio for now. Something like is working fine.

``lua
local function volume_emit()
  awful.spawn.easy_async_with_shell(
    "bash -c 'pamixer --get-volume'", function(stdout)
      local volume_int = tonumber(stdout)               -- integer
      awesome.emit_signal('signal::volume', volume_int) -- integer
    end)
end
```
